### ISSUE TITLE
Hide page header for printing

### ISSUE THREAD

**Issue by asemidotsky** [asemidotsky/dev-wiki#1]
Page header should be hided when printing pages from wiki.

**Comment by asemidotsky** [comment]
1.  Add stylesheet to layout.html
```xml
<link rel="stylesheet" type="text/css" href="print.css" media="print" />
```
2. Add css to print.css
```css
@media print
{    
    .no-print, .no-print *
    {
        display: none !important;
    }
}
```
[see more](https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page)
